require("./form.js");
require("./like-button.js");
require("./pagination.js");
require("./init.js");
require("./jquery.simplePagination");
require("./comments-list-events");
require("./init");
require("./moment-with-locales.min");
require("./storage-api");
